{{- if .Values.n8n.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "n8n.n8n.name" . }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    app.kubernetes.io/component: n8n
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "n8n.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: n8n
{{- end }}

