{{- if and .Values.readReplica.enabled .Values.readReplica.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgresql.fullname" . }}-read-replica-data
  labels:
    {{- include "postgresql.readReplica.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.readReplica.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.readReplica.persistence.size }}
  {{- if .Values.readReplica.persistence.storageClass }}
  {{- if (eq "-" .Values.readReplica.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.readReplica.persistence.storageClass }}
  {{- end }}
  {{- end }}
{{- end }}

