{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
{{- /* 
  NOTA: Este ServiceMonitor requer o Prometheus Operator instalado no cluster.
  Se você não tiver o Prometheus Operator, desabilite serviceMonitor.enabled no values.yaml
*/}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "postgresql.fullname" . }}-postgres-exporter
  labels:
    {{- include "postgresql.exporter.labels" . | nindent 4 }}
    {{- with .Values.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "postgresql.exporter.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    interval: {{ .Values.monitoring.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
    path: /metrics
{{- end }}

