{{- if .Values.pgbouncer.enabled }}
{{- $password := include "postgresql-simple.password" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql-simple.fullname" . }}-pgbouncer
  labels:
    {{- include "postgresql-simple.labels" . | nindent 4 }}
    app.kubernetes.io/component: pgbouncer
type: Opaque
stringData:
  userlist.txt: |
    "{{ .Values.postgresql.username }}" "{{ $password }}"
{{- end }}

