{{- if .Values.metabase.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "metabase.metabase.name" . }}
  labels:
    {{- include "metabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: metabase
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "metabase.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: metabase
{{- end }}

