{{- if and .Values.backupRestore.enabled (or .Values.backupRestore.restoreFromS3.bucket .Values.backupRestore.restoreFromDisk.path) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "postgresql.fullname" . }}-restore
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
    app.kubernetes.io/component: restore
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "postgresql.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: restore
    spec:
      restartPolicy: OnFailure
      containers:
      - name: restore
        image: postgres:{{ .Values.postgresql.image.tag }}
        imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
        command:
        - /bin/bash
        - -c
        - |
          set -e
          
          # Instalar dependências
          apt-get update && apt-get install -y awscli gzip && rm -rf /var/lib/apt/lists/*
          
          echo "Iniciando restore do PostgreSQL..."
          
          # Aguardar PostgreSQL estar pronto
          until PGPASSWORD="${POSTGRES_PASSWORD}" psql -h ${POSTGRES_HOST} -U ${POSTGRES_USER} -d postgres -c "SELECT 1" > /dev/null 2>&1; do
            echo "Aguardando PostgreSQL estar pronto..."
            sleep 2
          done
          
          # Download do backup
          BACKUP_FILE="/tmp/restore-backup.sql"
          {{- if .Values.backupRestore.restoreFromS3.bucket }}
          echo "Baixando backup do S3..."
          {{- if .Values.backup.s3.useIAMRole }}
          aws s3 cp s3://{{ .Values.backupRestore.restoreFromS3.bucket }}/{{ .Values.backupRestore.restoreFromS3.key }} ${BACKUP_FILE}
          {{- else }}
          export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}"
          export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}"
          {{- if .Values.backup.s3.endpoint }}
          export AWS_ENDPOINT_URL="${S3_ENDPOINT}"
          aws --endpoint-url=${S3_ENDPOINT} s3 cp s3://{{ .Values.backupRestore.restoreFromS3.bucket }}/{{ .Values.backupRestore.restoreFromS3.key }} ${BACKUP_FILE}
          {{- else }}
          export AWS_DEFAULT_REGION="{{ .Values.backupRestore.restoreFromS3.region }}"
          aws s3 cp s3://{{ .Values.backupRestore.restoreFromS3.bucket }}/{{ .Values.backupRestore.restoreFromS3.key }} ${BACKUP_FILE}
          {{- end }}
          {{- end }}
          {{- else }}
          echo "Usando backup local..."
          cp {{ .Values.backupRestore.restoreFromDisk.path }} ${BACKUP_FILE}
          {{- end }}
          
          # Descomprimir se necessário
          if [[ ${BACKUP_FILE} == *.gz ]]; then
            echo "Descomprimindo backup..."
            gunzip ${BACKUP_FILE}
            BACKUP_FILE="${BACKUP_FILE%.gz}"
          fi
          
          # Restaurar
          {{- if .Values.backupRestore.options.dropBeforeRestore }}
          echo "Removendo database existente..."
          PGPASSWORD="${POSTGRES_PASSWORD}" psql -h ${POSTGRES_HOST} -U ${POSTGRES_USER} -d postgres -c "DROP DATABASE IF EXISTS ${POSTGRES_DB};"
          {{- end }}
          
          {{- if .Values.backupRestore.options.createDatabase }}
          echo "Criando database se não existir..."
          PGPASSWORD="${POSTGRES_PASSWORD}" psql -h ${POSTGRES_HOST} -U ${POSTGRES_USER} -d postgres -c "SELECT 1 FROM pg_database WHERE datname='${POSTGRES_DB}'" | grep -q 1 || \
          PGPASSWORD="${POSTGRES_PASSWORD}" psql -h ${POSTGRES_HOST} -U ${POSTGRES_USER} -d postgres -c "CREATE DATABASE ${POSTGRES_DB};"
          {{- end }}
          
          echo "Restaurando backup..."
          PGPASSWORD="${POSTGRES_PASSWORD}" psql -h ${POSTGRES_HOST} -U ${POSTGRES_USER} -d ${POSTGRES_DB} < ${BACKUP_FILE}
          
          rm -f ${BACKUP_FILE}
          echo "Restore concluído com sucesso!"
        env:
        - name: POSTGRES_HOST
          value: {{ include "postgresql.fullname" . }}-postgresql
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "postgresql.fullname" . }}-postgresql
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "postgresql.fullname" . }}-postgresql
              key: postgres-password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: {{ include "postgresql.fullname" . }}-postgresql
              key: postgres-db
        {{- if .Values.backupRestore.restoreFromS3.bucket }}
        {{- if not .Values.backup.s3.useIAMRole }}
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "postgresql.fullname" . }}-backup-s3
              key: access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "postgresql.fullname" . }}-backup-s3
              key: secret-access-key
        {{- if .Values.backup.s3.endpoint }}
        - name: S3_ENDPOINT
          value: {{ .Values.backup.s3.endpoint | quote }}
        {{- end }}
        {{- end }}
        {{- end }}
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
{{- end }}

