apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql-simple.postgresql.name" . }}
  labels:
    {{- include "postgresql-simple.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: postgresql
    protocol: TCP
    name: postgresql
  selector:
    {{- include "postgresql-simple.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql

