{{- if and .Values.backup.enabled (eq .Values.backup.destination "s3") (not .Values.backup.s3.useIAMRole) }}
{{- if or .Values.backup.s3.accessKeyId .Values.backup.s3.secretAccessKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}-backup-s3
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
type: Opaque
data:
  access-key-id: {{ .Values.backup.s3.accessKeyId | b64enc | quote }}
  secret-access-key: {{ .Values.backup.s3.secretAccessKey | b64enc | quote }}
{{- end }}
{{- end }}

