{{- if .Values.readReplica.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.fullname" . }}-read-replica
  labels:
    {{- include "postgresql.readReplica.labels" . | nindent 4 }}
spec:
  type: {{ .Values.readReplica.service.type }}
  ports:
    - port: {{ .Values.readReplica.service.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "postgresql.readReplica.selectorLabels" . | nindent 4 }}
{{- end }}

