{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled .Values.monitoring.backend.enabled .Values.backend.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "app-js.backend.name" . }}
  labels:
    {{- include "app-js.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
    {{- with .Values.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "app-js.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  endpoints:
  - port: {{ .Values.monitoring.backend.port }}
    interval: {{ .Values.monitoring.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
    path: {{ .Values.monitoring.backend.path }}
{{- end }}

